### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: java.io.InputStream.readAllBytes()

### ISSUE THREAD

**Issue by IMB11** [SilverAndro/Modifold#4] opened 2022-09-03 22:22 UTC
Dunno what im doing wrong?

```
java -jar Modifold-2.2.1-all.jar --token %redacted% itsmineblock11 648562 653216
WARN: Unknown modrinth categories: [128x, 16x, 256x, 32x, 512x+, 64x, 8x-, audio, blocks, core-shaders, economy, entities, environment, fonts, game-mechanics, gui, items, management, minigame, mobs, modded, models, realistic, simplistic, social, themed, transportation, tweaks, vanilla-like]
WARN: These cannot be converted to with this version of the tool, make sure to apply them yourself if relevant
ONLY USE THIS TOOL ON PROJECTS YOU OWN
I built this for honest users who want to move off curseforge, I don't want to have to deal with people blaming me because someone stole their mods.
Modrinth moderation also checks for ownership anyways, so you're unlikely to get anywhere
? I understand this tool should only be used on my own projects Yes
Token was passed through CLI, using that
Modrinth login successful, user is mineblock11 (bOHH0P9Z)
Collecting curseforge projects
Collecting curseforge project info for project 648562 [DONE] (279ms)
Collecting curseforge project info for project 653216 [DONE] (1951ms)
Collecting existing modrinth projects
Done matching projects
 What data should be written to disk locally while transferring?
 What set of files should be transferred? All files
Creating modrinth projects from curseforge projects
Making modrinth project for ArrowCam (648562) [/] (306ms)Exception in thread "main" java.lang.NoSuchMethodError: java.io.InputStream.readAllBytes()[B
        at com.github.p03w.modifold.modrinth_api.ModrinthAPI$makeProject$1$1.invoke(ModrinthAPI.kt:87)
        at com.github.p03w.modifold.modrinth_api.ModrinthAPI$makeProject$1$1.invoke(ModrinthAPI.kt:84)
        at io.ktor.client.request.forms.MultiPartFormDataContent.writeTo(FormDataContent.kt:113)
        at io.ktor.client.engine.cio.UtilsKt.write(utils.kt:90)
        at io.ktor.client.engine.cio.UtilsKt.write$default(utils.kt:22)
        at io.ktor.client.engine.cio.Endpoint.writeRequestAndReadResponse(Endpoint.kt:147)
        at io.ktor.client.engine.cio.Endpoint.access$writeRequestAndReadResponse(Endpoint.kt:21)
        at io.ktor.client.engine.cio.Endpoint$makeDedicatedRequest$1$responseData$1.invokeSuspend(Endpoint.kt:122)
        at io.ktor.client.engine.cio.Endpoint$makeDedicatedRequest$1$responseData$1.invoke(Endpoint.kt)
        at io.ktor.client.engine.cio.Endpoint$makeDedicatedRequest$1$responseData$1.invoke(Endpoint.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
        at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
        at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
        at io.ktor.client.engine.cio.EndpointKt.handleTimeout(Endpoint.kt:269)
        at io.ktor.client.engine.cio.EndpointKt.access$handleTimeout(Endpoint.kt:1)
        at io.ktor.client.engine.cio.Endpoint$makeDedicatedRequest$1.invokeSuspend(Endpoint.kt:121)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Making modrinth project for ArrowCam (648562) [/] (321ms)
```

**Comment by SilverAndro** [comment] 2022-09-03 22:24
Hmmm, what java version are you running?

**Comment by SilverAndro** [comment] 2022-09-03 23:54
Tracked it down, seems like this is a j9 feature and kotlin just, lets you target j8 while calling it

https://docs.oracle.com/javase/9/docs/api/java/io/InputStream.html#readAllBytes--

So, will be fixed in next release to crash better:tm: but until then I suspect the issue is youve got j8 installed

**Comment by SilverAndro** [comment] 2022-09-04 15:03
Noticed added to README, ill close this once i have another release out

**Comment by SilverAndro** [comment] 2022-12-17 05:36
2.2.3 is out which gives a proper error message now 👍

**Closed as completed by SilverAndro** 2022-12-17 05:36 UTC
